# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterests',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinterests',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='friends.Interest'),
        ),
        migrations.DeleteModel(
            name='UserInterests',
        ),
    ]
