# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20161116_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interests',
            new_name='interest',
        ),
    ]
