# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20161116_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interest',
            new_name='interests',
        ),
    ]
